---
# tasks file for base-install

- name: update apt cache
  apt: update_cache=yes 
  become: yes

- name: ppa repo
  become: yes
  apt_repository: repo=ppa:ondrej/php

- name: install mysql
  become: yes
  apt: 
    name: "{{ item }}"
    state: latest
  with_items:
    - apache2
#    - nginx
    - mysql-server
    - python-mysqldb
    - php5
    - php5-mysql
    - php5-gd
    - php5-mcrypt
    - libssh2-php
#    - php7.0
#    - php7.0-mysql
#    - php7.0-gd
#    - php-ssh2
#    - php7.0-mcrypt
